seeder:
  file: ./seeder/seeder.rb
  disabled: false

parsers:
  - file: ./parsers/search.rb
    page_type: search
    disabled: false

  - file: ./parsers/product.rb
    page_type: product
    disabled: false

exporters:
  - exporter_name: products_0
    exporter_type: json
    collection: products
    write_mode: pretty_array