seeder:
  file: ./seeder/seeder.rb
  disabled: true

parsers:
  - file: ./parsers/search.rb
    page_type: search
    disabled: true

  - file: ./parsers/product.rb
    page_type: product
    disabled: true

exporters:
  - exporter_name: products
    exporter_type: json
    collection: products
    write_mode: pretty_array